//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        public int Booking_Id { get; set; }
        public string TourName { get; set; }
        
        public string Name { get; set; }
        public string Email { get; set; }
       
        public double MobileNumber { get; set; }
        
        public string Address { get; set; }
      
        public int NumberOfTickets { get; set; }
        public double TotalCost { get; set; }
        public string BookingStatus { get; set; }
    }
}
